name: Scheduled Test Run

on:
  push:
    branches:
      - main  # Puoi modificare il nome del branch se necessario
  schedule:
    - cron: '0 0 */5 * *'  # ogni 5 giorni

permissions:
  contents: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositoryls
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Gradle clean
        run: ./gradlew clean

      - name: Run Gradle tests
        run: ./gradlew :app:test

      - name: Configure Git
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"

      - name: Commit coverage matrix changes
        run: |
          git add app/coverage-matrix.json  # Updated path to the coverage matrix
          git commit -m "Update coverage matrix" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
